### PR TITLE
Add success_fee_bid to ProductParent

### PR DESCRIPTION
**Pull request by joemanley201**
ProductParent does not have the success_fee_bid column as of now. I am planning to add it today or tomorrow. Let me know if that is going to cause any issues

### CODE REVIEW

**Comment by joemanley201** [comment]
Should I wait till evening to add this field to the SDK too? 🤔

**Comment by jmtame** [comment]
I'm not sure if the timing matters here, but as a rule I wait until a migration is done before I add code in that is looking up the new columns.

**Comment by joemanley201** [comment]
Okay, I got it now 👍

**Comment by danieltlrlm** [comment]
Hello,
Is this related to Payouts timing out? I have tried during off business hours and still its timing out. Will this be corrected soon?

Thanks

Stuart Husney
732-730-6815 Ext 238
Direct-718-705-3906
Fax 718-934-1680
stuart@aeromaxdental.com<mailto:stuart@aeromaxdental.com>

**Comment by joemanley201** [comment]
@danieltlrlm This is not related to payouts. Please contact our support team if you have any issues with respect to Payouts.

**Pull request merged**
